export const FIELDS = [
  { key: "titel",            label: "Titel / Beschreibung",  type: "text",     col: "C" },
  { key: "trainingsteil",    label: "Trainingsteil",          type: "select",   col: "D", options: ["Aufwärmen","Hauptteil","Spielphase"] },
  { key: "schwerpunkt",      label: "Schwerpunkt",            type: "select",   col: "E", options: ["Koordination","Passspiel","Dribbling","Abschluss","Taktik","Kondition","Spielform","Sonstiges"] },
  { key: "tags",             label: "Tags",                   type: "text",     col: "F" },
  { key: "niveau",           label: "Alter / Niveau",         type: "select",   col: "G", options: ["U8","U10","U12","U14","U16","U19","Erwachsene","Alle"] },
  { key: "dauer",            label: "Dauer (Min.)",           type: "number",   col: "H" },
  { key: "spieleranzahl",    label: "Spieleranzahl gesamt",   type: "number",   col: "I" },
  { key: "aufstellungsform", label: "Aufstellungsform",       type: "select",   col: "L", options: ["Kreis","Reihen gegenüber","Freie Verteilung","Linie","Viereck"] },
  { key: "bewegungsstruktur",label: "Bewegungsstruktur",      type: "select",   col: "M", options: ["Mit Ball","Ohne Ball","Passdreiecke","1v1","2v1","Rondo","Spielform"] },
  { key: "intensitaet",      label: "Intensität",             type: "select",   col: "N", options: ["Niedrig","Mittel","Hoch"] },
  { key: "raumgroesse",      label: "Raumgröße / Feld",       type: "text",     col: "O" },
  { key: "feldform",         label: "Feldform",               type: "select",   col: "P", options: ["Rechteck","Quadrat","Kreis","Freiform"] },
  { key: "mitTor",           label: "Mit Tor?",               type: "select",   col: "Q", options: ["Ja","Nein"] },
  { key: "materialSpieler",  label: "Material je Spieler",    type: "text",     col: "R" },
  { key: "materialGruppe",   label: "Material je Gruppe",     type: "text",     col: "S" },
  { key: "bewertung",        label: "Bewertung (1–5)",        type: "number",   col: "U" },
  { key: "notizen",          label: "Notizen / Varianten",    type: "textarea", col: "V" },
];
